[build-system]
requires = ["poetry>=^0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyntc"
version = "0.16.0"
description = "SDK to simplify common workflows for Network Devices."
authors = ["NTC <info@networktocode.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
bigsuds = "^1.0.6"
f5-sdk = "^3.0.21"
junos-eznc = "^2.4.1"
netmiko = "^3.1"
paramiko = "^2.7"
pyeapi = "^0.8.3"
pynxos = "^0.0.5"
requests = "^2.23"
scp = "^0.13.2"
textfsm = "^1.1"

[tool.poetry.dev-dependencies]
coverage = "^5.1"
mock = "^4.0.2"
tox = "^3.15.0"
pylint = "^2.5.2"
flake8 = "^3.8.1"
black = "^20.8b1"
pydocstyle = "^5.0.2"
bandit = "^1.6.2"
coveralls = "^2.0.0"
pytest = "^5.4.2"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
  \.git
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
| blib2to3
| tests/data
)/
'''
